### ISSUE TITLE
Request: Remove # from URL

### ISSUE THREAD

**Issue by ascott1** [GSA/code-gov-web#119]
Hello! I'm excited to see this project out in the world. 

I have a small request that `#` be removed from the URL structure. I know this is an Angular convention, but it makes the URLs less legible and memorable. Also avoiding technology dictated URLs will make it easier to switch frameworks at a future date while preserving the links.

**Comment by lukad03** [comment]
@ascott1 Good point about link preservation. We're not using any form of backend currently, so the only way to rid of the # URL is to create a 404 HTML view that stores the intended path in `localStorage`, redirects to index, and then attempts to navigate to the original URL. Otherwise all links will be broken when shared.

We're still evaluating this, but for the foreseeable future we decided to keep the `#` in order to not abuse the 404's original intent. If you know of alternative solutions for Angular, do let us know!

**Comment by dracos** [comment]
As you already appear, if I understand it right, to be publishing this site as static to GitHub pages (as you say, you have no form of backend currently), an alternative solution that would work with Angular, and indeed any framework, would be to generate a static page for each agency, repository, help page, and so on. This would give you shareable URLs, that load much more quickly (helping with #129), that wouldn't have the hash anti-pattern URL that don't work at all if your JavaScript doesn't load/work – https://gdstechnology.blog.gov.uk/2016/09/19/why-we-use-progressive-enhancement-to-build-gov-uk/ .

**Comment by dracos** [comment]
I wrote a script that does this at https://github.com/dracos/code-gov-web/blob/gh-pages/scrape and it generates https://dracos.github.io/code-gov-web/

**Comment by lukad03** [comment]
@dracos In it's current state, this would likely work just fine. The API isn't updating regularly (and is outputting to `repos.json`), so the script could be run locally to generate these pages. However, once the API is being called directly, rendering static pages would result in a website that is dependent on running scripts (server-side or locally) at regular intervals to ensure the latest from the API is captured by these pages.

I'll discuss the short-term benefits vs. long-term trade-offs with the team and loop back here.

**Comment by dracos** [comment]
Thanks for replying; I'll comment on this in #129 as I think it's of more general relevance.

**Comment by cdoremus** [comment]
I noticed that LocationStrategy is set in app.module.ts to HashLocationStrategy (line 63). By default, Angular 2 uses PathLocationStrategy, so removing that line will remove the hash from all generated URLs. I could submit a PR if you want?

**Comment by dracos** [comment]
If you do that, without making the other pages exist on the server side (statically or otherwise), then no links will work when visited directly apart from the index page, as discussed above about shareable URLs. Doing something like that would certainly be good if possible, by providing links that work when JavaScript is unavailable for any reason, see the UK Government link above for more details on that.

**Comment by DanielJDufour** [comment]
Sorry. I won't be able to get to this with existing priorities.  I can't justify the heavy lift of changing our routing mechanisms without hard numbers that the hash is negatively impacting user retention.  AFAIK, we have no plans to change from Angular and Angular seems like a safe bet for the next few years.

That said, continual and organized user testing is something that we're looking into, so that we can identify the pain points of using code.gov.

**Comment by ascott1** [comment]
@DanielJDufour Just out of curiosity: what is the motivation of closing the issue if it is still an issue (even if not deemed a priority)?

I've collected best practices as they concern URLs [here](https://github.com/ascott1/ethical-web-dev/blob/master/web-apps-that-work-everywhere/02-url.md)

**Comment by DanielJDufour** [comment]
@ascott1 , thanks for the feedback.  I read your .md file on ethical and intuitive urls and I couldn't agree more.  I've done a lot of django / drf, so I'm all on board with object based urls.

I just started at code.gov as the front-end dev and am still working out what's the best way to manage GitHub issues.  I'm open to suggestions.  My main motivation is that I don't want to give false hope to people that I'm going to find time to solve an issue.  I think honesty is the best course. Honestly, the hash in the url isn't a priority for us at the moment.  I'm currently focused on improving the load time of the site and making sure it doesn't crash.

That said, I've also received feedback from other people that they don't like it when I close issues, so I'm re-evaluating things.  Would the `[Inactive] on hold` tag be more appropriate?  Do you have a suggestion for another tag that I can use to indicate things that are issues, but that I won't be able to get to because of current priorities (which I don't decide)?

And as always, open to PRs :-)

**Comment by DanielJDufour** [comment]
Is `backlog` a good tag for this use case?  I'm not sure what backlog means to everyone...

**Comment by dracos** [comment]
"I'm currently focused on improving the load time of the site and making sure it doesn't crash." - umm, you might want to reopen #129 then? :)

(An inactive tag sounds good to me, or backlog, anythig like that.)

**Comment by DanielJDufour** [comment]
@dracos , done

**Comment by ascott1** [comment]
@DanielJDufour I think something like `backlog` or `on-hold` definitely gets the point across without closing the issue. That said, if you deem something a non-issue that you don't plan to address, it would probably be better to close it. Thanks for all of your good work!

**Comment by DanielJDufour** [comment]
@ascott1 , thanks for the prompt response.  I still definitely consider it an issue.  I'll start using the `backlog` label for now going forward.  I reflected on it and I think `[Inactive] on-hold` might imply the wrong things and discourage people from submitting PRs, which are always welcome.  Thanks for your feedback and constructive dialogue :-)

**Comment by DanielJDufour** [comment]
Hi @ascott1 .  We fixed the urls.  Here's an example: https://code.gov/projects/dol_opa_android_doldatasdk

Thanks!
