### ISSUE TITLE
Activity out of date

### ISSUE THREAD

**Issue by jmcarp** [GSA/code-gov-web#261]
It looks like the data behind the `Activity` section are months out of date, at least going by the first example I looked at: https://code.gov/#/explore-code/repos/28643936. This page shows the latest activity as from November, but https://github.com/18F/analytics.usa.gov has much more recent activity. Is this expected?

**Comment by okamanda** [comment]
Hi @jmcarp Thanks for raising this issue. We intended for our API to pull the activity data directly from the repo hosting service (e.g., Github), but unfortunately we have to work through a security review before we can release this feature to the public.

Would love your thoughts on what we should replace this in the meantime. If relevant, you can add comment here: #250

**Comment by jmcarp** [comment]
Not sure if the activity feed is still broken, but if it is, I would suggest hiding that section of the page until it's working again. What's the latest on this @okamanda @yozlet ?

**Comment by DanielJDufour** [comment]
Thanks for bringing this to our attention.  I'm closing this issue because AFAIK, any information like that is being generate by the agencies themselves and stored in their code.json.  Specifically, look at the lastModified date in the schema.  I'm going to close this for now, but if there is still an issue with an agency's information, feel free to let them know or you can let us know and we'll connect you :-)
