### ISSUE TITLE
I am surprised, Why there is no inheritance ?

### ISSUE THREAD

**Issue by amineparis** [GSA/code-gov-web#368]
Using inheritance between services, components, etc would be greate to define common behaiviours

**Comment by DanielJDufour** [comment]
@amineparis , yes, great point! We are looking at inheritance as a way to reduce duplication in our code and improve maintainability.  I'm going to close this issue because it's very general and open up issues for specific components and services.  If you like, feel free to open up another issue on a specific component or service that you think would benefit from inheritance.  We also consider pull requests.  Thank you for your feedback!
