### ISSUE TITLE
Code.json upgrader is not working

### ISSUE THREAD

**Issue by froi** [GSA/code-gov-web#369]
@IanLee1521 was trying to upgrade a sample __code.json__ but the __upgrade__ button seems to not be working correctly. Once pressed it shows no feedback of success or error and produces no output.

Looking at the dev console an error shows up, see attached screenshot:
![image](https://user-images.githubusercontent.com/1918027/33948181-41b059ce-dff4-11e7-94e3-77eadc33620c.png)

**Comment by BalajiJBcs** [comment]
You have made a typo in function name it seems that's why it shows TypeError in the console. The console defines TypeError : . ... is not a function. So when it is attempted to call a value for the function, but the value is not actually a function. Some code expects you to provide a function, but that didn't happen.

**Comment by DanielJDufour** [comment]
We will not be fixing the upgrader as all partially-compliant and compliant agencies have already upgraded their schemas.
