### ISSUE TITLE
Host Images on Sub Domain

### ISSUE THREAD

**Issue by DanielJDufour** [GSA/code-gov-web#397]
## Expected Behavior

Images should load without any queuing or stalling

## Current Behavior

There's about 100 milliseconds stalls on my browser before loading each agency logo on https://code.gov/#/explore-code/agencies/AID

## Possible Solution

Host images on a subdomain like img.code.gov.  Browsers limit how many active connections a user can have to one domain. Browsers usually treat sub-domains as separate for this purpose.

## Steps to Reproduce (for bugs)

1. Open dev tools' Networking Tab
2. Go to https://code.gov/#/explore-code/agencies/AID

## Context

Makes page load slower

## Your Environment

* Browser Name and version: Chrome on Chrome OS Version 62.0.3202.97 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Chrome on Chrome OS Version 62.0.3202.97 (Official Build) (64-bit)

**Comment by jbjonesjr** [comment]
✋ someone who did some heavy web-app image optimization at one point in my life...

Might I suggest creating a sprite so that you can load the image once and use CSS to display all the logos? This reduces total connections, connection overhead and some scale with tcp window resizing and other low level stuff. I bet someone in 18F or USDS already has a sprite somewhere...

**Comment by DanielJDufour** [comment]
Thanks @jbjonesjr ! That's a great idea!  I'll definitely look into doing that.

**Comment by DanielJDufour** [comment]
Not directly relevant as we are no longer displaying agency logos after the rearchitecture and redesign of browse projects and search results pages.  We may revisit this in the future and take some of the good advice from Jamie.
