### ISSUE TITLE
help-wanted section not loading in internet explorer

### ISSUE THREAD

**Issue by SSAgov** [GSA/code-gov-web#456]
## Current Behavior
https://code.gov/#/help-wanted not loading correctly when using internet explorer as shown here:
![image](https://user-images.githubusercontent.com/28628385/36747924-5b8dc834-1bc4-11e8-946a-83ce1dd771b9.png)

## Your Environment
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Win10

**Comment by DanielJDufour** [comment]
@SSAgov , thank you for catching this! We'll look at this right away.

**Comment by DanielJDufour** [comment]
I've identified the issue.  The issue is that internet explorer does not support the `includes` function of arrays.  I will fix this within the next day or two by rewriting the code the uses `includes` to use `indexOf` instead.

Webpack or Babel should have transpiled this to indexOf or an ES5 alternative, so we might need to reconfigure to work on older versions.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by DanielJDufour** [comment]
@SSAgov , help-wanted should be working on code.gov now.  Please clear your cache and try again.  If it's not working, pleas, reopen the issue! Thank you very much! :-)
