### ISSUE TITLE
SBA Projects Count Discrepancy Reported by SBA

### ISSUE THREAD

**Issue by RicardoAReyes** [GSA/code-gov-web#541]
SBA has experienced project discrepancy on the project count. In which the sba.gov/code.json file has 5 releases but the Code.gov website shows 7. 

Discrepancy Reported
http://sba.gov/code.json | 5 releases 
https://www.code.gov/#/explore-code/agencies/SBA | *7 release

* The 7 releases was reported but I have not been able to replicate the issue. 

System Details:
Windows PC
Browser: 
Internet Explorer v. TBD

**Comment by rebel-one** [comment]
How to replicate this issue: 

Go to the Search functionality of the home page and **search** for "SBA". Seven projects are displayed at the moment (5 from the agency and 2 that contain the word "SBA"). 

Because the agency of the projects is not displayed this caused **confusion** at the SBA because it listed more projects than the agency had open sourced. 

Proposed solution: Display the agency of the results in a search.

**Comment by DanielJDufour** [comment]
Thanks for the feedback! I'll discuss this with the team and keep you updated on our progress :-)

**Comment by DanielJDufour** [comment]
Hi, @rebel-one . We are now displaying the agency in the card in the search results. Here's a card from https://code.gov/search?page=1&query=SBA&size=10&sort=best_match:

![image](https://user-images.githubusercontent.com/4313463/49469240-0ba11180-f7d5-11e8-964d-67387b58592c.png)

I'm going to close an issue, but feel free to open up a new issue on our new repo https://github.com/GSA/code-gov-front-end/issues  if you run into any more problems.  Thanks! :-)
