### ISSUE TITLE
404 Error on MyRTK

### ISSUE THREAD

**Issue by TeeMorris** [GSA/code-gov-web#651]
Your issue may already be reported!
Please search on the [issue track](../) before creating one.

## Expected Behavior

I went to My Right to Know (MyRTK) on Code.gov to find out more about it.
## Current Behavior

When I clicked on the "Visit Repo" button, it gave me a 404 error.
## Possible Solution

Check links.
## Steps to Reproduce (for bugs)

1. Go to https://code.gov/#!/explore-code/agencies/EPA/repos/epa_usepa_my_right_to_know_myrtk_
2. Click the Visit Repo button
3.
4.

## Context

This project would be perfect for the practical collection of projects I am compiling, but the repo link is bad, apparently.
## Your Environment

* Version used:
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Mac OS X
* Link to your project:

**Comment by DanielJDufour** [comment]
@TeeMorris , thank you for the great catch!

There is a typo in the code.json for the EPA, which you can view here.  The link to the code.json is here https://epa.gov/code.json (which redirects to https://www.epa.gov/sites/production/files/buckeye_symlinks/digital_strategy_2017/code.json).

The issue is that the repo name is misspelled in the code.json.  It's accidentally spelled `https://github.com/USEPA/My-Right-To-Know-MyRTK-`, but should be `https://github.com/USEPA/My-Right-To-Know--MyRTK-` with two dashes.

![image](https://user-images.githubusercontent.com/4313463/45317835-2848e880-b509-11e8-89c3-ae0b4f6dd5b3.png)

@RicardoAReyes , tagging you in case you want to bring it up with EPA.

**Comment by DanielJDufour** [comment]
https://code.gov/projects/epa_usepa_my_right_to_know_myrtk_ is working
